azure_sql_rg="AzureSQL-RG"
location="Korea Central"
azure_sql_server_name="hyugosqlserver"
azure_sql_version="12.0"
azure_sql_admin_username="azureuser"
azure_sql_admin_password="qwer1234!@#$"
azure_sql_db="Todos"
azure_sql_db_size_gb=2
azure_sql_db_sku="basic"